export interface RawCandidate {
  id: string;
  name: string;
  role: string;
  skills: string;
  experience: string;
  specialization?: string;
  portfolio?: string;
  cv?: string;
  email?: string;
  whatsapp?: string;
  location?: string;
  hourlyRate?: number;
  salaryExpectation?: number;
}

export const records: RawCandidate[] = [
  // --- DESIGN TALENT (From CSV 1 & Resumes) ---
  {
    id: "ID-001",
    name: "Muhammad Faizan",
    role: "UI/UX or Graphic Designer",
    skills: "Photoshop, Figma, XD, and Illustrator",
    experience: "3 year",
    specialization: "Graphic Design, Illustration, Product Design",
    portfolio: "https://www.behance.net/MuhammadFazanDesigns",
    cv: "https://drive.google.com/file/d/1rWO613fgXLZQ7yGWa_a6ztEeGzk2dK9U/view?usp=sharing",
    email: "",
    whatsapp: "",
    location: "Islamabad, Pakistan"
  },
  {
    id: "ID-002",
    name: "Muhammad Tayyab",
    role: "UI/UX Designer",
    skills: "Figma, Adobe XD, Framer, Adobe Photoshop, HTML, CSS, JavaScript, React.js, Python, MongoDB",
    experience: "1.5 year",
    specialization: "Mobile apps, Websites, Landing pages, Crypto & Food Delivery UI",
    portfolio: "https://www.behance.net/muhammad_tayyab_ch",
    cv: "",
    email: "muhammadtayyab2900@gmail.com",
    whatsapp: "0311-6793619",
    location: "Sahiwal, Pakistan"
  },
  {
    id: "ID-003",
    name: "Mustafizur Rahman Jaidul",
    role: "UI/UX & Product Designer",
    skills: "Figma, SaaS Design, Mobile Apps, Prototyping",
    experience: "3 year",
    specialization: "Designing SaaS, e-commerce, fintech, web and mobile products",
    portfolio: "https://www.behance.net/jaiduldesigner",
    cv: "",
    email: "",
    whatsapp: "",
    location: "Bangladesh"
  },
  {
    id: "ID-004",
    name: "Md. Shakib Islam",
    role: "UI/UX Designer",
    skills: "Figma (Expert), Adobe Photoshop, Adobe Illustrator, Wireframing, Prototyping, User Research",
    experience: "1+ year",
    specialization: "User-friendly mobile apps and websites, UI design",
    portfolio: "https://behance.net/captainshakib",
    cv: "https://drive.google.com/file/d/1uCdFzJXpZhAzxoUuYBBdHiSOEvMEPVUC/view?usp=sharing",
    email: "captainshakib@gmail.com",
    whatsapp: "01332041298",
    location: "Dhaka, Bangladesh"
  },
  {
    id: "ID-005",
    name: "Adeleke Toluwase",
    role: "UI/UX Designer",
    skills: "Visual Design, Brand Identity, UI/UX, Motion Effect, Adobe Creative Cloud, Corel Draw, Canva",
    experience: "4 year",
    specialization: "Visual Design, Brand Identity, Motion Effect",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1FuzpGtxjFxr1bCUtpHdNxGBtnFvvCG53/view?usp=sharing",
    email: "adeleketoluwase21@gmail.com",
    whatsapp: "+2349136347503",
    location: "Abuja, Nigeria"
  },
  {
    id: "ID-006",
    name: "Osawota oghenetega",
    role: "UI/UX Designer",
    skills: "Figma, Adobe Photoshop, Adobe Illustrator",
    experience: "1 year",
    specialization: "UI/UX Design, Wireframing",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1zK7ufC5bruAF8JOBlv-XlqBo2dqY1S_j/view?usp=drive_link",
    email: "tegaosawota94@gmail.com",
    whatsapp: "08039931368",
    location: "Lagos, Nigeria"
  },
  {
    id: "ID-007",
    name: "Eridani Wahyu Nugraha",
    role: "UI/UX Designer",
    skills: "Figma, Jira, Trello, ClickUp",
    experience: "4 year",
    specialization: "UI/UX Design, Agile Product Workflow",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1OhIytHLrDaEP_sPFXfXUdkjFzvzXL7EJ/view?usp=sharing",
    email: "eridani.works@gmail.com",
    whatsapp: "+6289669433120",
    location: "Semarang, Central Java, Indonesia"
  },
  {
    id: "ID-008",
    name: "Azmat Ullah",
    role: "UI/UX Designer",
    skills: "Figma, Adobe Photoshop, Adobe Illustrator, Premiere Pro",
    experience: "3 year",
    specialization: "UI/UX Design, Multimedia Graphics",
    portfolio: "https://www.behance.net/azmatullah",
    cv: "https://drive.google.com/file/d/1nToG9bJQLZrs8EnV2TnoNQPdLAVV0TEX/view?usp=sharing",
    email: "azmatullah.okz1@gmail.com",
    whatsapp: "+923089427993",
    location: "Islamabad, Pakistan"
  },
  {
    id: "ID-009",
    name: "Uzair Ahmed",
    role: "UI/UX Designer",
    skills: "Figma, Adobe Photoshop, Adobe Illustrator, Adobe XD",
    experience: "2 year",
    specialization: "UI/UX Design, Wireframing & Prototyping",
    portfolio: "https://behance.net/ozairahmed1",
    cv: "https://drive.google.com/file/d/13pOrisSx3JBYRj3pn0E6jdwMTyCZfSDa/view?usp=sharing",
    email: "uzairahmed171@gmail.com",
    whatsapp: "+923104050104",
    location: "Lahore, Pakistan"
  },

  // --- SOFTWARE & DEVELOPER TALENT (From CSV 2 & Resumes) ---
  {
    id: "ID-010",
    name: "Mudassar Farooq",
    role: "Mobile App Developer",
    skills: "React Native, TypeScript, JavaScript/ES6+, Redux Toolkit, Firestore, Real-time Database, REST APIs, React Hooks, iOS & Android, Xcode, Android Studio, Git",
    experience: "3 years",
    specialization: "iOS & Android Phone Applications",
    portfolio: "",
    cv: "https://drive.google.com/file/d/16bzWFxH1N9GvC6sWkApWMGEX-qbhVjtj/view?usp=sharing",
    email: "mudassarfarooq931@gmail.com",
    whatsapp: "+923011688483",
    location: "Lahore, Pakistan"
  },
  {
    id: "ID-011",
    name: "Sumair Irshad",
    role: "AI Engineer & Data Scientist",
    skills: "Python, C++, Machine Learning, Deep Learning, Computer Vision, NLP, CNNs, YOLOv8, RAG Systems, LangGraph, LangChain, BERT, TensorFlow, PyTorch, Node.js, FastAPI, Flutter",
    experience: "6 Years",
    specialization: "Head of AI Engineering, RAG Pipelines, Computer Vision, Full-Stack",
    portfolio: "https://github.com/sumair218",
    cv: "https://drive.google.com/file/d/1T5WEFTN8jOw9Y2wxtih-uFBL_xYhgZie/view?usp=sharing",
    email: "sumairirshad52@gmail.com",
    whatsapp: "+923554467620",
    location: "Gilgit, Pakistan"
  },
  {
    id: "ID-012",
    name: "Nahoor Tahir",
    role: "Full Stack & AI App Developer",
    skills: "AI Integration, Mobile Development, Frontend Development, State & Data, Backend & APIs, Integration, Performance, Tools & Practices",
    experience: "5 years",
    specialization: "AI-Integrated Full Stack Web & Mobile Apps",
    portfolio: "",
    cv: "https://drive.google.com/file/d/18dAOmIeruJk5h-ZgHLqBau9mUTk4Ffcf/view?usp=sharing",
    email: "nahoor98@gmail.com",
    whatsapp: "+923180970708",
    location: "Islamabad, Pakistan"
  },

  // --- INFRASTRUCTURE & SYSTEMS ENGINEERS (From CSV 3 & Resumes) ---
  {
    id: "ID-013",
    name: "Xolisani Madolo",
    role: "NOC Technician & IT Support Engineer",
    skills: "IR Support, IT Field Technician, Network Monitoring (IBM Netcool, iMaster NCE, Nokia DWDM), Cisco, Avaya, Office 365, Active Directory, Azure, Fortinet NSE 1/2",
    experience: "10 yrs",
    specialization: "Network Management Center, Telecom NOC, Enterprise Assurance",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1Y9DmJWK7stgKuKsf8EP0VcNMy9qafNRr/view?usp=sharing",
    email: "xolisanimadolo@gmail.com",
    whatsapp: "+27655165320 / +27810554671",
    location: "Cape Town, South Africa"
  },
  {
    id: "ID-014",
    name: "Pedro Henrique silva peixoto",
    role: "Data Engineer",
    skills: "Data Interpretation & Analysis, Python, SQL, Cloud Data, Leadership",
    experience: "10+ year",
    specialization: "6+ yr interpreting/analyzing data, 10+ yr IT experience, leadership",
    portfolio: "",
    cv: "https://drive.google.com/file/d/11gno6v7TGuJVHLve_pZVk0x6cXddKEou/view?usp=sharing",
    email: "phenriquepeixoto@gmail.com",
    whatsapp: "+5561983230843",
    location: "Paraisopolis - MG - Brazil"
  },
  {
    id: "ID-015",
    name: "Baljinder pal Singh",
    role: "Infrastructure & Technical Leadership Engineer",
    skills: "Technical Leadership & Service Management, Cyber security/GRC, Cloud & Infrastructure, AI & Productivity, DevOps & Automation, ITSM/MSP Tools",
    experience: "12+ year",
    specialization: "Technical Leadership, GRC, Cloud & Infrastructure",
    portfolio: "",
    cv: "https://docs.google.com/document/d/1xOwKXos6DHyn1pp6fVW7BPo07T0BoWfS",
    email: "singhbaljinder065@gmail.com",
    whatsapp: "+447887183789",
    location: "Derby, United Kingdom"
  },
  {
    id: "ID-016",
    name: "Rayen Aissa",
    role: "IT Maintenance / Support Technician",
    skills: "Hardware and Troubleshooting, Diagnostic & Technical Analysis, Windows & Linux, Network (CISCO), Cloud Fundamentals",
    experience: "3 years",
    specialization: "Hardware troubleshooting, Cisco Network, Windows/Linux",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1V6y0q6DP5YBDzyiA2IyqCTyOjGtdAkj-/view?usp=sharing",
    email: "AissaRayen23@gmail.com",
    whatsapp: "+21628786431",
    location: "Tunis, Tunisia"
  },
  {
    id: "ID-017",
    name: "Mohammad Amin Saleem",
    role: "Senior System, Network & Security Engineer",
    skills: "Networking, Security, Operations & Tools, Automation, Firewalls",
    experience: "16+ yr",
    specialization: "Enterprise Systems, Network Architecture, Cyber Security",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1bSOPI9_LBP_A0xQ5xDrTSAu6D73eE9LS/view?usp=sharing",
    email: "saleem.sfr@sfr.fr",
    whatsapp: "+33642598893",
    location: "Pecquencourt, France"
  },
  {
    id: "ID-018",
    name: "Andrii Hontaruk",
    role: "IT Support Technician L1/L2",
    skills: "IT Support L1/L2, Hardware & Software Maintenance, Troubleshooting",
    experience: "22+ yrs",
    specialization: "Tier 1 & Tier 2 Enterprise IT Support",
    portfolio: "",
    cv: "https://drive.google.com/file/d/1Rfzja0lHJoSjPuZLcA9X_Hms-BuAB8xb/view?usp=sharing",
    email: "a.gontaruk@gmail.com",
    whatsapp: "+41767231548",
    location: "Geneva, Switzerland"
  },

  // --- EXPANDED RESUME TALENT ROSTER (From User Documents) ---
  {
    id: "ID-019",
    name: "Romicha Parvin",
    role: "Frontend Developer",
    skills: "HTML5, CSS3, JavaScript, TypeScript, React.js, Next.js, Redux Toolkit, Tailwind CSS, Shadcn/ui, Node.js, Express.js, NestJs, MongoDB, PostgreSQL",
    experience: "1 year",
    specialization: "Frontend Developer (React.js, Next.js, TypeScript, Redux)",
    portfolio: "https://github.com/romicha",
    cv: "",
    email: "romicha617@gmail.com",
    whatsapp: "+8801775897617",
    location: "Dhaka, Bangladesh"
  },
  {
    id: "ID-020",
    name: "Pirah Asad",
    role: "UI/UX Designer | Graphic Designer",
    skills: "Figma, Adobe XD, Adobe Photoshop, Canva, Prototyping, Wireframing, Illustration & Vector Design, WCAG Accessibility, Design Systems",
    experience: "3.5+ years",
    specialization: "UI/UX for Web & Mobile, Design Systems, User Research",
    portfolio: "https://www.behance.net",
    cv: "",
    email: "pirahasad15@gmail.com",
    whatsapp: "+92 336 2441809",
    location: "Karachi, Pakistan"
  },
  {
    id: "ID-021",
    name: "Abdul Rehman",
    role: "Junior UI/UX Designer",
    skills: "Figma, Adobe Photoshop, Adobe Illustrator, Canva, Wireframing, Prototyping, Responsive Design, Auto Layout, Components",
    experience: "3 months",
    specialization: "Interface designing for web and mobile, Auto Layout, Color Theory",
    portfolio: "https://linkedin.com/in/abdulrehman-9846b8383",
    cv: "",
    email: "rehmandesigner85@gmail.com",
    whatsapp: "+92-322-3192059",
    location: "Karachi, Pakistan"
  },
  {
    id: "ID-022",
    name: "Hamza Fayyaz",
    role: "UI/UX Designer",
    skills: "Figma, Figma AI, Sketch, FigJam, Google Stitch, Miro, Adobe XD, Adobe Photoshop, Adobe Illustrator, Design Systems",
    experience: "2+ years",
    specialization: "Web, Mobile App, Dashboard and Email Design, WCAG Accessibility",
    portfolio: "https://dribbble.com/hamzasiddiqi",
    cv: "",
    email: "khawaja.hamza2014@gmail.com",
    whatsapp: "+92 320 6745983",
    location: "Multan, Pakistan"
  },
  {
    id: "ID-023",
    name: "Umar Daraz",
    role: "UI/UX Designer | AI Creative Designer",
    skills: "Figma, Shopify, User Research, Graphic Design, Responsive Design, Claude, ChatGPT, n8n, AI-Assisted Design",
    experience: "2+ years",
    specialization: "Web & Mobile Interfaces, Design Systems, AI Automation",
    portfolio: "https://www.behance.net/umarsheikhh",
    cv: "",
    email: "umersheikhh001@gmail.com",
    whatsapp: "+92 317 2010156",
    location: "Lahore, Pakistan"
  },
  {
    id: "ID-024",
    name: "Areeba Nadeem",
    role: "UI/UX Designer",
    skills: "Figma, FigJam, Adobe XD, Photoshop, Illustrator, Canva, Miro, Notion, Zeplin, HTML, CSS, User Research",
    experience: "1+ year",
    specialization: "User-Centered Digital Experiences, AI Learning Platforms, Food Delivery UI",
    portfolio: "https://areebanadeem.com",
    cv: "",
    email: "areebanadeem4845@gmail.com",
    whatsapp: "+92 335 7874845",
    location: "Rahim Yar Khan, Pakistan"
  },
  {
    id: "ID-025",
    name: "Senthu Kulavarathan",
    role: "IT Support Analyst | Microsoft 365 & Infrastructure",
    skills: "Microsoft 365, Exchange Online, Intune, Entra ID, Windows Server, SCCM/MECM, Active Directory, Group Policy, PowerShell, ITIL",
    experience: "5+ years",
    specialization: "Enterprise Microsoft 365, Endpoint Management, Cloud Transformation",
    portfolio: "https://linkedin.com/in/senthuran92",
    cv: "",
    email: "senthuran92@hotmail.com",
    whatsapp: "07778882620",
    location: "London, UK"
  },
  {
    id: "ID-026",
    name: "Samiya Ahsan",
    role: "Senior UX/UI Designer",
    skills: "Figma, Framer, Maze, Adobe Illustrator, Adobe Photoshop, Lovable, Google Stitch, AI Studio, Design Systems, AI-Integrated Design",
    experience: "4+ years",
    specialization: "SaaS Platforms, Mobile Apps, Enterprise Design Systems",
    portfolio: "https://behance.net/samiyaahsan",
    cv: "",
    email: "samiya.ahsan99@gmail.com",
    whatsapp: "+923127516413",
    location: "Islamabad, Pakistan"
  },
  {
    id: "ID-027",
    name: "Zain Ali",
    role: "UI/UX Designer & Full Stack Developer",
    skills: "Figma, User Research, Wireframing, Python, JavaScript, React.js, HTML/CSS, SQL (MySQL), Node.js, MongoDB",
    experience: "1+ year",
    specialization: "Full Stack Web Apps & UI/UX Product Design",
    portfolio: "https://github.com",
    cv: "",
    email: "zainali.creative@gmail.com",
    whatsapp: "+92 327 2190027",
    location: "Karachi, Pakistan"
  },
  {
    id: "ID-028",
    name: "Eemaan Afzal",
    role: "Lead UI/UX Designer",
    skills: "Figma, Figma Make, Google Stitch, Claude, Gemini, Photoshop & Illustrator, Auto Layout, Components, Variants",
    experience: "4+ years",
    specialization: "Lead Product Design, 30+ Live Apps, Urdu Fonts Ecosystem, Healthcare & AI Apps",
    portfolio: "https://www.behance.net",
    cv: "",
    email: "emanafzal13@gmail.com",
    whatsapp: "+923218744047",
    location: "Sargodha, Pakistan"
  },
  {
    id: "ID-029",
    name: "M. Abubakar",
    role: "UI/UX Designer",
    skills: "Figma, Adobe Photoshop, Adobe Illustrator, Interface Designing, Design Systems, Wireframing & Prototyping",
    experience: "3+ years",
    specialization: "Digital products, Community platforms, Business dashboards",
    portfolio: "https://behance.net",
    cv: "",
    email: "abubakarlala061@gmail.com",
    whatsapp: "0306-0464338",
    location: "Islamabad, Pakistan"
  },
  {
    id: "ID-030",
    name: "Zain Lodhi",
    role: "UI/UX Designer | AI Product Design Specialist",
    skills: "Figma, Adobe XD, Adobe Illustrator, Adobe Photoshop, InDesign, Premiere Pro, After Effects, AI/SaaS Design",
    experience: "6+ Years",
    specialization: "AI-Powered SaaS products, Chatbots, Conversational UI, Analytics Dashboards",
    portfolio: "https://www.behance.net/zainlodhi",
    cv: "",
    email: "zainlodhi70@gmail.com",
    whatsapp: "0305-7970399",
    location: "Lahore, Pakistan"
  },
  {
    id: "ID-031",
    name: "Urwah Tamoor",
    role: "Senior UI/UX & Graphic Designer",
    skills: "Figma, Adobe Photoshop, Adobe Illustrator, Canva, Adobe Premiere, AI Prompting, Dashboard & Admin Panels",
    experience: "4+ years",
    specialization: "E-commerce experiences, Modern UI systems, Brand identity",
    portfolio: "https://behance.net/urwasoduzai",
    cv: "",
    email: "urwahsoduzai@gmail.com",
    whatsapp: "03285564247",
    location: "Rawalpindi, Pakistan"
  },
  {
    id: "ID-032",
    name: "Josue Rocha Junior",
    role: "Intune & Infrastructure Engineer / IT Support Analyst",
    skills: "Microsoft Intune (MDM/MAM), Active Directory, Azure AD / Entra ID, Windows Server, Group Policy, MFA, Cisco, Fortinet, SCCM, ServiceNow",
    experience: "10+ years",
    specialization: "Endpoint Management, Intune, Enterprise IT Infrastructure & Migration",
    portfolio: "https://www.linkedin.com/in/josue-rocha-junior-36bb15114/",
    cv: "",
    email: "jrbr033@gmail.com",
    whatsapp: "+353 83 335 1664",
    location: "Dublin, Ireland"
  },
  {
    id: "ID-033",
    name: "Ahmed Ndiaye",
    role: "Network Field Installation Engineer | CCNA",
    skills: "Cisco, Juniper, HPE/Aruba, Routing & Switching, TCP/IP, VLANs, Fortinet, Palo Alto, Forcepoint, SevOne NMS, Nagios",
    experience: "3+ years",
    specialization: "Field engineering, Multi-vendor network hardware installations & rollouts",
    portfolio: "",
    cv: "",
    email: "ahmed94.an.an@gmail.com",
    whatsapp: "07756 794947",
    location: "Leeds, UK"
  },
  {
    id: "ID-034",
    name: "Farhan Muhammad Qureshi",
    role: "Network Administrator & IT Field Engineer",
    skills: "Network Security, Structured Cabling, Active Directory Server, DNS, Group Policy, Cisco, Juniper, Huawei, HP, Data Centre Design",
    experience: "15+ years",
    specialization: "Enterprise Network Administration, Structured Cabling, Data Center Support",
    portfolio: "",
    cv: "",
    email: "Farhanmq@live.com",
    whatsapp: "+44-745-5413977",
    location: "Karachi, Pakistan / Sharp Brains UK"
  },
  {
    id: "ID-035",
    name: "Thanuj Kumar Gottipati",
    role: "IT Support Engineer",
    skills: "Windows 11/10, Linux, Microsoft Intune, Office 365, Wireshark, Jira, Active Directory, Azure AD, MD 102, AZ-900",
    experience: "3+ years",
    specialization: "1st/2nd Line Support, Endpoint Administration, Dell/Getronics Hardware",
    portfolio: "https://linkedin.com/in/thanuj-kumar-gottipati",
    cv: "",
    email: "thanujkumargottipati@gmail.com",
    whatsapp: "+447774864292",
    location: "London, UK"
  },
  {
    id: "ID-036",
    name: "Muhammad Umair Ahmed",
    role: "IT Operations Manager & IT Delivery Consultant",
    skills: "Microsoft 365, Azure Active Directory / Entra ID, Intune, ServiceNow, Jira, ITIL, Windows migration, PMP, Data Centers",
    experience: "10+ years",
    specialization: "IT Service Delivery Management, Infrastructure Operations, EMEA Enterprise Projects",
    portfolio: "https://www.linkedin.com/in/muhammad-umair-ahmed-007/",
    cv: "",
    email: "ahmed.muhammadumair@gmail.com",
    whatsapp: "+358401940407",
    location: "Helsinki, Finland"
  },
  {
    id: "ID-037",
    name: "Arif Chilla Poyil",
    role: "Systems & Microsoft 365 Administrator | Network & Firewall Engineer",
    skills: "Fortinet FortiGate, Aruba Switching & Wireless, Microsoft 365 & Exchange Online, Active Directory, VPN (IPsec/SSL), Azure, Acronis",
    experience: "5+ years",
    specialization: "Network Security, Fortinet, Aruba, Enterprise Windows Server",
    portfolio: "https://linkedin.com",
    cv: "",
    email: "arifmuhammed01z@gmail.com",
    whatsapp: "+968 90223449",
    location: "Muscat, Oman"
  },
  {
    id: "ID-038",
    name: "Umar Zayyar",
    role: "Full Stack & Mobile App Developer",
    skills: "React, React Native, Node.js, AWS, Python, FastAPI, HTML5, CSS3, JavaScript, Machine Learning",
    experience: "3 years",
    specialization: "Mobile & Web Applications, POS Systems, CRM Development",
    portfolio: "",
    cv: "",
    email: "umarzayyar62@gmail.com",
    whatsapp: "03034990628",
    location: "Lahore, Pakistan"
  },
  {
    id: "ID-039",
    name: "Rafia Adeel",
    role: "AI / ML Engineer · Full-Stack Developer",
    skills: "TensorFlow, PyTorch, scikit-learn, XGBoost, OpenCV, MediaPipe, LangChain, FAISS, RAG, React.js, Django REST Framework, FastAPI, PostgreSQL, MongoDB",
    experience: "2+ years",
    specialization: "AI-powered products, Computer Vision, Voice RAG Assistants, ML Pipelines",
    portfolio: "https://github.com",
    cv: "",
    email: "rafiaaa37@gmail.com",
    whatsapp: "0305-4672038",
    location: "Lahore, Pakistan"
  },
  {
    id: "ID-040",
    name: "Juan Ignacio Gómez",
    role: "UI/UX Designer & Visual Designer",
    skills: "Figma, Photoshop, Illustrator, Blender 3D, UX Research, Design Thinking, Wireframing, Micro-interactions",
    experience: "3+ years",
    specialization: "AI Platform UI Design, Covertly AI, 3D & Visual Interfaces",
    portfolio: "",
    cv: "",
    email: "juanigomez853@gmail.com",
    whatsapp: "+54 264-4460155",
    location: "San Juan Capital, Argentina"
  },
  {
    id: "ID-041",
    name: "Asma Naeem",
    role: "UI/UX Designer | Product Designer",
    skills: "Figma, User Research, Wireframing, Prototyping, UI Design, UX Design, Design Systems, Responsive Design",
    experience: "2+ years",
    specialization: "Web and Mobile Interfaces, Scalable Design Solutions",
    portfolio: "https://behance.net/asma-naeem",
    cv: "",
    email: "asmanaeem342@gmail.com",
    whatsapp: "+92 333 1300159",
    location: "Rawalpindi / Islamabad, Pakistan"
  },
  {
    id: "ID-042",
    name: "Amna Alam",
    role: "UI/UX Designer",
    skills: "Figma, Wireframing, User Flows, Interactive Prototyping, Design Systems, Auto Layout, HTML, CSS, Bootstrap",
    experience: "2+ years",
    specialization: "Sleep Tracker & Digital Agency UI, Design Systems",
    portfolio: "https://behance.net",
    cv: "",
    email: "amnaalam387@gmail.com",
    whatsapp: "+92 3243346371",
    location: "Lahore, Pakistan"
  },
  {
    id: "ID-043",
    name: "Obadare Samson Oluwole",
    role: "Product Designer (UI/UX) | Interaction Designer",
    skills: "Figma, CreatieAI, Miro, Sketch, Adobe Creative Suite, Wireframing, User Research, HTML, CSS, Flutterflow, Framer",
    experience: "4+ years",
    specialization: "Fintech solutions, PayPetal, Logistics & Payment Platforms",
    portfolio: "https://www.elshamzy.com.ng/",
    cv: "",
    email: "Obadare.samson01@gmail.com",
    whatsapp: "+234 7050388560",
    location: "Lagos State, Nigeria"
  },
  {
    id: "ID-044",
    name: "Irfan Haider",
    role: "UI/UX Designer (Team Lead)",
    skills: "Figma, Mobile & Web App Design, Dashboard Design, Landing Page Design, User Research, Design Systems",
    experience: "3 years",
    specialization: "SaaS, Fintech, Design Team Leadership, High-Converting Interfaces",
    portfolio: "https://www.linkedin.com/in/irfan-haider-uiux-designer/",
    cv: "",
    email: "haiderirfan4050@gmail.com",
    whatsapp: "+92 3554162445",
    location: "Gilgit, Pakistan"
  },
  {
    id: "ID-045",
    name: "Mohamed Ehab Gomaa",
    role: "IT Support Specialist & Infrastructure Engineer",
    skills: "Microsoft 365, Intune, Cisco Switching & Routing, Active Directory, CCNA Enterprise, POS Systems, VMware",
    experience: "6+ years",
    specialization: "System Administration, Network Troubleshooting, Majid Al Futtaim Group Support",
    portfolio: "https://linkedin.com/in/mohamed-ehab-690449189",
    cv: "",
    email: "mohamedehab9292@gmail.com",
    whatsapp: "+201019791779",
    location: "Cairo, Egypt"
  },
  {
    id: "ID-046",
    name: "Ahmed Abdelnaby Oraby",
    role: "IT Technical Support & Help Desk Specialist",
    skills: "Networking (CCNA, CCNP, Routing & Switching, VLANs), VoIP Systems (Issabel PBX), CCTV Installation, IT Troubleshooting",
    experience: "3+ years",
    specialization: "Orange Egypt Service Desk, VoIP Configuration, CCTV & Network Support",
    portfolio: "https://linkedin.com/in/عرابي-احمد-a2328224a",
    cv: "",
    email: "araby9792@gmail.com",
    whatsapp: "01552614682",
    location: "Toukh, Qalyubia, Egypt"
  },
  {
    id: "ID-047",
    name: "Aurelian-Florin Mircea",
    role: "Senior IT Engineer",
    skills: "IT Hardware/Software Installation, Troubleshooting, Telecommunications Systems, Perimeter & Network Security, CCTV, Project Management",
    experience: "15+ years",
    specialization: "Large-scale Computer Systems, Security Ecosystems, IT Project Management",
    portfolio: "",
    cv: "",
    email: "m_rely@yahoo.com",
    whatsapp: "0465 62 77 12",
    location: "Antwerp, Belgium"
  },
  {
    id: "ID-048",
    name: "Nisar Ahmed",
    role: "IT Support Engineer | IT Asset Manager | Data Center Engineer",
    skills: "IT Asset Management, Windows 10/11 Migration, Active Directory, Microsoft Intune, SCCM, Microsoft 365, Tier III/IV Data Center Operations, Cisco, ServiceNow",
    experience: "10+ years",
    specialization: "Data Center Engineering, IT Asset Lifecycle Across EMEA, Equinix Facilities",
    portfolio: "",
    cv: "",
    email: "nisarahmedpak1981@gmail.com",
    whatsapp: "+31 657371846",
    location: "Amsterdam, Netherlands"
  },
  {
    id: "ID-049",
    name: "Asif Nasim",
    role: "Senior Network & Infrastructure Engineer",
    skills: "Cisco Nexus, Catalyst 9300, Fortinet, Palo Alto, CCNP Enterprise, Azure AZ-104, Python, Ansible, Terraform, BGP, OSPF, MPLS, SD-WAN",
    experience: "12+ years",
    specialization: "Enterprise Network Architecture, Government Data Center Security, Zero Trust",
    portfolio: "https://linkedin.com/in/asif-nasim831",
    cv: "",
    email: "asif.nasim001@gmail.com",
    whatsapp: "+44 7745 873407",
    location: "Luton, UK"
  },
  {
    id: "ID-050",
    name: "Luige Bandibas",
    role: "ICT Support Engineer | IT Field Support Technician",
    skills: "IT Support, Windows 11/10 Upgrades, Microsoft 365, Azure Management, Intune MDM, Cisco, Kaseya, ServiceNow, Active Directory, ACS Certified",
    experience: "7+ years",
    specialization: "Desktop Infrastructure, Intune MDM, Hardware QA & Field Services",
    portfolio: "",
    cv: "",
    email: "luigebandibas@gmail.com",
    whatsapp: "0430 074 375",
    location: "Elizabeth Vale, SA, Australia"
  }
];
